using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using TMPro;

public class InteractionManager : MonoBehaviour
{
    public float checkRate = 0.05f;
    private float lastCheckTime;
    public float maxCheckDistane;
    public LayerMask layerMask;

    private GameObject curInteractGameObject;
    private IInteractable curIntearctable;

    public TextMeshProUGUI promptText;
    private Camera cam;

    private void Start()
    {
        cam = Camera.main;
    }

    private void Update()
    {
        if(Time.time - lastCheckTime > checkRate)
        {
            lastCheckTime = Time.time;
        }
    }

}

public interface IInteractable
{
    string GetInteractPrompt();
    void OnInteract();
}
